org.gradle.jvmargs=-Xmx4096M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

# JDK 21 (Android Studio JBR) per locale; in CI usa il setup-java
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=false
