org.gradle.jvmargs=-Xmx4096M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

# JDK 21 locale (Temurin); in CI usa il setup-java
org.gradle.java.home=C\:\\Program Files\\Eclipse Adoptium\\jdk-21.0.12.101-hotspot
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=false
